pipeline {
    agent any 
    stages {
        stage('PortTest') { 
            steps {
                sh 'sudo lsof -i:8000'
                
            }
        }
        stage('TokenTest') { 
            steps {
                sh ' curl -X POST  http://127.0.0.1:8000/login -d \'{"username": "admin","password": "admin"}\''

            }
        }
        // stage('FailPortTest') { 
        //     steps {
        //         sh 'sudo lsof -i:8086'
                
        //     }
        // }
        stage('Artifact') { 
            steps {
                archiveArtifacts artifacts: '**'
            }
        }
        stage('Upload-Artifact'){
            steps {
                nexusArtifactUploader artifacts: [[
                    artifactId: 'ArtifactPipelin1', 
                    classifier: '', 
                    file: '/var/lib/jenkins/workspace/pipeline-2/arch-img', 
                    type: 'raw']], 
                credentialsId: '044f2262-242c-4c4c-89e0-668160443363', 
                groupId: 'MyPipelineArtifact', 
                nexusUrl: 'https://f6ec-191-102-199-176.ngrok.io/repository/artifact-with-maven/', 
                nexusVersion: 'nexus3', 
                protocol: 'http', 
                repository: 'artifact-with-maven', 
                version: '1.0.0'
            }
        }
    }
}
