pipeline {
    agent any 
    stages {
        stage('PortTest') { 
            steps {
                sh 'sudo lsof -i:8000'
                
            }
        }
        stage('TokenTest') { 
            steps {
                sh ' curl -X POST  http://127.0.0.1:8000/login -d \'{"username": "admin","password": "admin"}\''

            }
        }
        // stage('FailPortTest') { 
        //     steps {
        //         sh 'sudo lsof -i:8086'
                
        //     }
        // }
        stage('Artifact') { 
            steps {
                archiveArtifacts artifacts: '**'
            }
        }
        stage('Create tar.gz file'){
            steps{
                sh 'tar -cvzf pipeline-2.tar.gz /var/lib/jenkins/workspace/pipeline-2'
            }
            
        }
        // stage('Upload-Artifact-Nexus'){
        //     steps {
        //         nexusArtifactUploader artifacts: [[
        //             artifactId: 'ArtifactPipelin1', 
        //             classifier: '', 
        //             file: '/var/lib/jenkins/workspace/pipeline-2/pipeline-2.tar.gz', 
        //             type: 'tar.gz']], 
        //         credentialsId: '044f2262-242c-4c4c-89e0-668160443363', 
        //         groupId: 'MyPipelineArtifact', 
        //         nexusUrl: '192.168.33.12:8081', 
        //         nexusVersion: 'nexus3', 
        //         protocol: 'http', 
        //         repository: 'artifact-with-maven', 
        //         version: '1.0.1'
        //     }
        // }
        stage('Upload-Artifact-GitHub'){
            steps{
                script {
                    def exists = fileExists '/var/lib/jenkins/workspace/pipeline-2/artifact-jenkins-git'

                    if (exists) {
                        println "FOUND"
                    } else {
                        println "File doesn't exist"
                    }
                }
                sh 'testing if file exists'
                
                //sh 
            }
        }
    }
}
